import {chromium} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync,mkdirSync,readFileSync,existsSync} from 'node:fs';
import {createServer} from 'node:http';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import assert from 'node:assert/strict';
const tmp=mkdtempSync(join(tmpdir(),'paperlex-browser-'));
const server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'31992',PAPERLEX_DATA:tmp},stdio:['ignore','pipe','pipe']});
 let browser,model;
function fixturePDF(){
 const stream='BT /F1 18 Tf 55 740 Td (Transient electric fields in plasma) Tj 0 -35 Td /F1 12 Tf (Abstract) Tj 0 -24 Td (We investigate transient electric fields in atmospheric pressure plasma.) Tj 0 -24 Td (Electron density was measured using optical spectroscopy.) Tj 0 -24 Td (The results demonstrate improved temporal resolution.) Tj ET';
 const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [4 0 R 6 0 R 8 0 R] /Count 3 >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];
 for(let n=1;n<=3;n++){const content=stream.replace('Transient electric fields in plasma',`Page ${n}: Transient electric fields in plasma`);objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${5+(n-1)*2} 0 R >>`,`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`);}
 let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const offset=Buffer.byteLength(pdf),count=objects.length+1;pdf+=`xref\n0 ${count}\n0000000000 65535 f \n`+offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${count} /Root 1 0 R >>\nstartxref\n${offset}\n%%EOF`;return Buffer.from(pdf);
}
try{
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);setTimeout(()=>reject(Error('startup timeout')),15000).unref();});
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.stack);});
 await page.goto('http://127.0.0.1:31992');await page.getByRole('heading',{name:'文献工作台'}).waitFor();assert.equal((await page.locator('.app-sidebar').boundingBox()).y,0);
 await page.locator('#newProject').click();await page.locator('#projectForm [name=name]').fill('低温等离子体 · 电场诊断');await page.locator('#projectForm [name=topic]').fill('non-thermal plasma, electric field diagnostics');await page.getByRole('button',{name:'创建项目',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#toast')?.textContent.includes('项目已创建'));
 await page.locator('#fileInput').setInputFiles([{name:'Transient electric fields in atmospheric pressure plasma.pdf',mimeType:'application/pdf',buffer:fixturePDF()},{name:'Optical diagnostics of non-equilibrium discharges.txt',mimeType:'text/plain',buffer:Buffer.from('Abstract Optical spectroscopy provides a non-invasive measurement of transient electric fields. The electron density in plasma was measured with nanosecond resolution. Results show that the electric field increases during the ionization wave. Keywords plasma diagnostics spectroscopy. Introduction The electric field controls electron transport in atmospheric pressure discharges.')}]);
 await page.locator('tr[data-doc]').first().waitFor();await page.waitForFunction(()=>document.querySelectorAll('tr[data-doc]').length===2);
 await page.locator('tr[data-doc]').filter({hasText:'Transient electric fields'}).click();await page.locator('[data-paper-page="1"] .textLayer').waitFor();assert.equal(await page.locator('#textMode').count(),0);
 const selectPDF=async(n,phrase)=>{await page.waitForFunction(n=>document.querySelector('[data-paper-page="'+n+'"] .textLayer')?.textContent.includes('plasma'),n);await page.locator('[data-paper-page="'+n+'"] .textLayer').evaluate((el,phrase)=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())&&(!node.textContent.includes(phrase)||(phrase==='plasma'&&!node.textContent.startsWith('We investigate')))){}if(!node)throw Error('selection text missing');const at=node.textContent.indexOf(phrase),r=document.createRange();r.setStart(node,at);r.setEnd(node,at+phrase.length);const s=window.getSelection();s.removeAllRanges();s.addRange(r);el.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));},phrase);await page.locator('#selectionBar').waitFor();};
 await page.locator('#toggleReaderHeader').click();assert.equal(await page.locator('.reader-top').isVisible(),false);await page.locator('#toggleReaderHeader').click();await page.locator('#sideFontUp').click();await page.locator('#sideFontUp').click();
 await selectPDF(1,'plasma');await page.locator('#selectionLookup').click();await page.locator('#meaning').waitFor();await page.locator('#saveWord').click();await page.waitForFunction(()=>document.querySelector('#wordCount').textContent==='1');await page.locator('#meaning').fill('用户补充：用于诊断的等离子体');await page.locator('#saveWord').click();await page.waitForFunction(()=>document.querySelector('#meaningSaveState')?.textContent.includes('已保存到'));
 await selectPDF(1,'electric fields');await page.locator('[data-paper-page="1"] .textLayer').evaluate(el=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())&&node.textContent!=='Abstract'){}const range=window.getSelection().getRangeAt(0);range.setEnd(node,node.textContent.length);el.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));});await page.locator('#selectionNote').click();await page.locator('#noteForm [name=note]').fill('PDF 第一页批注');await page.getByRole('button',{name:'保存批注',exact:true}).click();await page.locator('.pdf-note-rect').first().waitFor();
 await page.locator('#nextPage').click();await selectPDF(2,'electric fields');await page.locator('#selectionNote').click();await page.locator('#noteForm [name=note]').fill('第二页滚动批注');await page.getByRole('button',{name:'保存批注',exact:true}).click();await page.locator('[data-paper-page="2"] .pdf-note-rect').first().waitFor();
 const notes=(await (await page.request.get('http://127.0.0.1:31992/api/state')).json()).annotations;assert.ok(notes.every(n=>n.anchor.rects.length));assert.equal(await page.locator('.pdf-note-rect').first().evaluate(el=>getComputedStyle(el).borderBottomWidth),'1px');assert.equal(notes.find(n=>n.note==='PDF 第一页批注').index,-1);
 await page.locator('[data-view=vocabulary]').click();await page.locator('[data-card-source]').click();await page.locator('[data-paper-page="1"] .vocab-mark').first().waitFor();assert.equal(await page.locator('.pdf-jump-rect').count(),0);const savedCards=(await(await page.request.get('http://127.0.0.1:31992/api/state')).json()).cards;assert.equal(savedCards[0].context,'We investigate transient electric fields in atmospheric pressure plasma.');assert.equal(await page.locator('#textMode').count(),0);
 await page.reload();await page.locator('#resumeReader').click();await page.locator('[data-paper-page="1"] .pdf-note-rect').first().waitFor();const initialWidth=await page.locator('[data-paper-page="1"] canvas').evaluate(c=>c.width);await page.locator('#zoomIn').click();await page.waitForFunction(w=>document.querySelector('[data-paper-page="1"] canvas')?.width>w,initialWidth);await page.locator('#zoomReset').click();
 await page.locator('#pagedLayout').click();await page.locator('[data-paper-page="1"] canvas').waitFor();await page.locator('[data-note-jump]').filter({hasText:'第二页滚动批注'}).click();await page.locator('.note-target').first().waitFor();assert.equal(await page.locator('.note-target').first().evaluate(el=>el.closest('[data-paper-page]').dataset.paperPage),'2');assert.equal(await page.locator('[data-paper-page]').count(),1);
 await page.locator('#continuousLayout').click();await page.locator('[data-paper-page="2"] canvas').waitFor();assert.equal(await page.locator('[data-paper-page]').count(),3);
 await page.locator('#lookupInput').fill('electric field');await page.getByRole('button',{name:'查询释义'}).click();await page.locator('#contextResults .context-card').first().waitFor();await page.locator('.term-editor summary').click();await page.locator('#preferredTerm').fill('瞬态电场');await page.locator('#saveTerm').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('专业译法已保存'));
 await page.locator('[data-delete-note]').first().click();await page.locator('#deleteConfirm[open]').waitFor();const rect=await page.locator('#deleteConfirm').boundingBox();assert.ok(Math.abs(rect.y+rect.height/2-1050/2)<3);await page.locator('#deleteConfirm [value=cancel]').click();assert.equal(await page.locator('[data-delete-note]').count(),2);
 mkdirSync(resolve('test-results'),{recursive:true});await page.screenshot({path:'test-results/reader.png',fullPage:true});
 model=createServer(async(req,res)=>{let body='';for await(const part of req)body+=part;const selected=JSON.parse(body).messages?.at(-1)?.content;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:selected==='Abstract'?'摘要':'等离子体中的瞬态电场。通过光谱测量电子密度，并分析实验结果。'}}]}));});await new Promise(r=>model.listen(0,'127.0.0.1',r));
 const currentSettings=(await (await page.request.get('http://127.0.0.1:31992/api/state')).json()).settings;await page.request.post('http://127.0.0.1:31992/api/settings',{data:{...currentSettings,aiEnabled:true,aiUrl:`http://127.0.0.1:${model.address().port}/v1`,aiModel:'test-fixture'}});
 const editor=await browser.newPage({viewport:{width:1440,height:1000}});editor.on('pageerror',e=>errors.push(e.message));await editor.goto('http://127.0.0.1:31992'+await page.locator('#fullTranslation').getAttribute('href'));await editor.locator('[data-block]').first().click();await editor.locator('#translation').fill('人工校对：等离子体中的瞬态电场');await editor.locator('#save').click();await editor.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('已保存'));await editor.locator('#start').click();await editor.waitForFunction(()=>document.querySelector('#progress').textContent.startsWith('翻译完成'),{},{timeout:20000});await editor.reload();await editor.locator('[data-block]').first().click();assert.equal(await editor.locator('#translation').inputValue(),'人工校对：等离子体中的瞬态电场');assert.equal(await editor.locator('#pageSelect option').count(),3);await editor.locator('#pageSelect').selectOption('3');await editor.waitForFunction(()=>document.querySelectorAll('.translated').length>0);await editor.screenshot({path:'test-results/translation.png',fullPage:true});
 const topBefore=await editor.locator('main').evaluate(el=>el.getBoundingClientRect().top);await editor.locator('#toggleTranslationHeader').click();assert.equal(await editor.locator('.toolbar').isVisible(),false);assert.ok(await editor.locator('main').evaluate(el=>el.getBoundingClientRect().top)<topBefore);await editor.reload();assert.equal(await editor.locator('.toolbar').isVisible(),false);await editor.locator('#toggleTranslationHeader').click();assert.equal(await editor.locator('#translationProvider option[value=deepl]').count(),1);
 assert.equal(await editor.locator('#translationLayout').count(),0);await editor.setViewportSize({width:1440,height:700});await editor.locator('#sourceFitPage').click();assert.ok(await editor.locator('.source-scroll').evaluate(el=>{const a=el.getBoundingClientRect(),b=el.querySelector('canvas').getBoundingClientRect();return b.top>=a.top&&b.bottom<=a.bottom+1&&b.right<=a.right+1;}));await editor.locator('#sourceFitWidth').click();for(let n=0;n<3;n++)await editor.locator('#sourceZoomIn').click();assert.ok(await editor.locator('.source-scroll').evaluate(el=>el.scrollHeight>el.clientHeight));await editor.locator('.source-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);assert.ok(await editor.locator('.source-scroll').evaluate(el=>el.querySelector('canvas').getBoundingClientRect().bottom<=el.getBoundingClientRect().bottom));await editor.locator('#sourceFitPage').click();await editor.setViewportSize({width:1440,height:1000});assert.ok(await editor.locator('.flow-block').count());await editor.locator('.flow-block').first().click();const firstId=await editor.locator('.flow-block').first().getAttribute('data-id');assert.equal(await editor.locator('.source-highlight').first().getAttribute('data-block-id'),firstId);await editor.locator('.flow-block').nth(1).click();assert.ok(await editor.locator('.source-highlight').count()>=1);assert.notEqual(await editor.locator('.source-highlight').getAttribute('data-block-id'),firstId);assert.equal(await editor.locator('.flow-block.selected').count(),1);
 const flowDownload=editor.waitForEvent('download');await editor.locator('#exportHtml').click();const flowFile=await flowDownload;await flowFile.saveAs(join(tmp,'flow.html'));const flowHTML=readFileSync(join(tmp,'flow.html'),'utf8');assert.match(flowHTML,/class="flow-page"/);assert.match(flowHTML,/人工校对：等离子体中的瞬态电场/);const flowPreview=await browser.newPage();await flowPreview.setContent(flowHTML);assert.equal(await flowPreview.locator('.flow-block').first().evaluate(el=>getComputedStyle(el).position),'static');await flowPreview.locator('.flow-block p').first().evaluate(el=>el.textContent='科研译文自动换行。'.repeat(500));assert.ok(await flowPreview.locator('.flow-block').first().evaluate(el=>el.clientHeight>500&&el.scrollHeight<=el.clientHeight+1));await flowPreview.close();await editor.screenshot({path:'test-results/flow-highlight.png',fullPage:true});const jsonDownload=editor.waitForEvent('download');await editor.locator('#exportJson').click();const jsonResult=await jsonDownload;await jsonResult.saveAs(join(tmp,'draft.json'));assert.equal(JSON.parse(readFileSync(join(tmp,'draft.json'),'utf8')).status,'complete');await editor.close();await new Promise(r=>model.close(r));model=null;await page.request.post('http://127.0.0.1:31992/api/settings',{data:currentSettings});
 console.log('PASS: 模拟模型完成三页全文翻译、人工修改持久化、原版图像与完整译文导出。');
 await page.request.post('http://127.0.0.1:31992/api/settings',{data:{...currentSettings,online:true}});await page.route('**/api/corpus',route=>route.fulfill({json:{query:'plasma',results:[{id:'paper:fixture',engine:'Europe PMC',title:'Scientific plasma paper',year:2025,url:'https://europepmc.org/',sentences:['Abstract plasma sentence.'],fulltextAvailable:true}]}}));await page.route('**/api/fulltext',route=>route.fulfill({json:{results:[{text:'Plasma measurements were taken in the experiment.',section:'Methods'}]}}));await page.reload();await page.locator('#resumeReader').click();await page.locator('#lookupInput').fill('plasma');await page.getByRole('button',{name:'查询释义'}).click();await page.locator('#meaning').waitFor();await page.waitForFunction(()=>!document.querySelector('#lookupProgress'));await page.route('**/api/lookup',async route=>{const data=route.request().postDataJSON();if(data.phase!=='details')return route.continue();await route.fulfill({json:{q:data.q,kind:'word',meaning:'等离子体',local:[],senses:[],error:'补充词典失败：测试网络不可达'}});});await page.locator('#dictionaryDetails').click();await page.locator('.dictionary-feedback').waitFor();assert.match(await page.locator('.dictionary-feedback').textContent(),/网络不可达/);assert.equal(await page.locator('#meaning').inputValue(),'用户补充：用于诊断的等离子体');await page.locator('#corpusTab').click();await page.locator('#corpusEngine').selectOption('europepmc');await page.locator('#loadCorpus').click();await page.locator('[data-fulltext]').click();await page.waitForFunction(()=>document.querySelector('[data-body]')?.textContent.includes('Methods'));assert.match(await page.locator('[data-body]').textContent(),/论文正文/);await page.request.post('http://127.0.0.1:31992/api/settings',{data:currentSettings});
 await page.locator('[data-view=vocabulary]').click();await page.locator('[data-delete-card]').first().click();await page.locator('#deleteConfirm[open]').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('.vocab-card').count(),1);await page.locator('[data-view=review]').click();await page.locator('#retentionTarget').selectOption('0.95');await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('记忆目标'));assert.equal(await page.locator('.memory-panel svg').count(),1);await page.screenshot({path:'test-results/memory.png',fullPage:true});await page.locator('#reveal').click();await page.locator('[data-rating=good]').click();await page.getByRole('heading',{name:'当前没有到期词汇'}).waitFor();
 await page.locator('[data-view=library]').click();await page.mouse.move(800,100);await page.screenshot({path:'test-results/library.png',fullPage:true});
 await page.setViewportSize({width:760,height:1000});await page.screenshot({path:'test-results/narrow.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.deepEqual(errors,[]);console.log('PASS: PDF/TXT 导入、原版文本层、选词批注、释义收藏、跨文献例句、翻卡评分、窄屏布局；无浏览器异常。');
 const help=await browser.newPage({viewport:{width:1280,height:900}});await help.goto('http://127.0.0.1:31992/guide');await help.getByRole('heading',{name:'3. 普通联网：最简单的配置方法',exact:true}).waitFor();await help.screenshot({path:'test-results/guide.png',fullPage:false});await help.close();console.log('PASS: 双模式、文本/PDF 缩放、右栏字号、跨页面及刷新后继续阅读、音标与双语多义项、项目术语、重提文字保留批注。');
 if(process.env.LIVE_NETWORK==='1'){
   const current=await (await page.request.get('http://127.0.0.1:31992/api/state')).json();
   await page.request.post('http://127.0.0.1:31992/api/settings',{data:{...current.settings,online:true}});
   const lookup=await (await page.request.post('http://127.0.0.1:31992/api/lookup',{data:{q:'electric field',projectId:current.projects[0].id}})).json();assert.ok(lookup.meaning.includes('电场'));assert.equal(lookup.error,'');
   const corpus=await (await page.request.post('http://127.0.0.1:31992/api/corpus',{data:{q:'electric field',projectId:current.projects[0].id}})).json();assert.ok(Array.isArray(corpus.results));console.log('LIVE corpus results:',corpus.results.length);
   const sentence=await (await page.request.post('http://127.0.0.1:31992/api/lookup',{data:{q:'The electric field increases during the discharge.',kind:'sentence',projectId:current.projects[0].id}})).json();assert.match(sentence.translation,/[\u4e00-\u9fff]/);assert.ok(sentence.technicalTerms.some(t=>t.zh==='瞬态电场'));console.log('LIVE full sentence:',sentence.translation);
   const imported=await (await page.request.post('http://127.0.0.1:31992/api/import',{data:{name:'online-summary.txt',projectId:current.projects[0].id,content:Buffer.from('Abstract We measure the electric field in plasma using spectroscopy. The results demonstrate that electron density increases during the discharge.').toString('base64')}})).json();
   let complete;const deadline=Date.now()+90000;
   do{complete=await (await page.request.get('http://127.0.0.1:31992/api/document/'+imported.id)).json();if(complete.summary.status!=='processing')break;await new Promise(r=>setTimeout(r,500));}while(Date.now()<deadline);
   assert.equal(complete.summary.status,'ready',complete.summary.error);assert.match(complete.summary.zh,/[\u4e00-\u9fff]/);console.log('PASS: 实际联网释义、科研论文检索、导入后自动生成中英文概要。');
 }
}finally{if(model)await new Promise(r=>model.close(r));if(browser)await browser.close();await new Promise(r=>{if(server.exitCode!==null)return r();server.once('exit',r);server.kill();});rmSync(tmp,{recursive:true,force:true});}
