import {chromium} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import assert from 'node:assert/strict';
const tmp=mkdtempSync(join(tmpdir(),'paperlex-browser-'));
const server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'31992',PAPERLEX_DATA:tmp},stdio:['ignore','pipe','pipe']});
 let browser;
function fixturePDF(){
 const stream='BT /F1 18 Tf 55 740 Td (Transient electric fields in plasma) Tj 0 -35 Td /F1 12 Tf (Abstract) Tj 0 -24 Td (We investigate transient electric fields in atmospheric pressure plasma.) Tj 0 -24 Td (Electron density was measured using optical spectroscopy.) Tj 0 -24 Td (The results demonstrate improved temporal resolution.) Tj ET';
 const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [4 0 R 6 0 R 8 0 R] /Count 3 >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];
 for(let n=1;n<=3;n++){const content=stream.replace('Transient electric fields in plasma',`Page ${n}: Transient electric fields in plasma`);objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${5+(n-1)*2} 0 R >>`,`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`);}
 let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const offset=Buffer.byteLength(pdf),count=objects.length+1;pdf+=`xref\n0 ${count}\n0000000000 65535 f \n`+offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${count} /Root 1 0 R >>\nstartxref\n${offset}\n%%EOF`;return Buffer.from(pdf);
}
try{
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);setTimeout(()=>reject(Error('startup timeout')),15000).unref();});
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:31992');await page.getByRole('heading',{name:'文献工作台'}).waitFor();assert.equal((await page.locator('.app-sidebar').boundingBox()).y,0);
 await page.locator('#newProject').click();await page.locator('#projectForm [name=name]').fill('低温等离子体 · 电场诊断');await page.locator('#projectForm [name=topic]').fill('non-thermal plasma, electric field diagnostics');await page.getByRole('button',{name:'创建项目',exact:true}).click();
 await page.locator('#fileInput').setInputFiles([{name:'Transient electric fields in atmospheric pressure plasma.pdf',mimeType:'application/pdf',buffer:fixturePDF()},{name:'Optical diagnostics of non-equilibrium discharges.txt',mimeType:'text/plain',buffer:Buffer.from('Abstract Optical spectroscopy provides a non-invasive measurement of transient electric fields. The electron density in plasma was measured with nanosecond resolution. Results show that the electric field increases during the ionization wave. Keywords plasma diagnostics spectroscopy. Introduction The electric field controls electron transport in atmospheric pressure discharges.')}]);
 await page.locator('tr[data-doc]').first().waitFor();await page.waitForFunction(()=>document.querySelectorAll('tr[data-doc]').length===2);
 await page.locator('tr[data-doc]').filter({hasText:'Transient electric fields'}).click();await page.locator('#readingText').waitFor();
 assert.ok(await page.locator('#readingText .academic-title').count());const originalTextSize=await page.locator('#readingText').evaluate(el=>parseFloat(getComputedStyle(el).fontSize));await page.locator('#zoomIn').click();assert.ok(await page.locator('#readingText').evaluate((el,old)=>parseFloat(getComputedStyle(el).fontSize)>old,originalTextSize));await page.locator('#zoomReset').click();
 await page.locator('#sideFontUp').click();await page.locator('#sideFontUp').click();assert.equal(await page.locator('#sideFontValue').textContent(),'16px');
 await page.locator('#lookupInput').fill('plasma');await page.getByRole('button',{name:'查询释义'}).click();await page.locator('#meaning').waitFor();assert.ok((await page.locator('#meaning').inputValue()).includes('等离子体'));await page.locator('#saveWord').click();await page.waitForFunction(()=>document.querySelector('#wordCount').textContent==='1');
 assert.equal(await page.locator('.sense-card').count(),2);assert.match(await page.locator('.pronunciation').textContent(),/plæzmə/);assert.ok(await page.locator('.sense-card blockquote').count()>=2);await page.locator('#pronounceWord').click();
 await page.locator('#readingText').evaluate(el=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())&&!node.textContent.includes('electric fields')){}const offset=node.textContent.indexOf('electric fields');const r=document.createRange();r.setStart(node,offset);r.setEnd(node,offset+15);const s=window.getSelection();s.removeAllRanges();s.addRange(r);el.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));});
 await page.locator('#selectionNote').click();await page.locator('#noteForm [name=note]').fill('记录瞬态电场的测量方法，比较其他论文的时间分辨率。');await page.getByRole('button',{name:'保存批注',exact:true}).click();await page.locator('mark').waitFor();
 assert.equal(await page.locator('[data-paper-page]').count(),3);
 await page.locator('#paper').hover();await page.mouse.wheel(0,800);await page.waitForFunction(()=>document.querySelector('#prevPage').nextElementSibling.textContent==='2 / 3');
 await page.locator('[data-paper-page="2"] .paper-text').evaluate(el=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())&&!node.textContent.includes('electric fields')){}const offset=node.textContent.indexOf('electric fields'),r=document.createRange();r.setStart(node,offset);r.setEnd(node,offset+15);const s=window.getSelection();s.removeAllRanges();s.addRange(r);el.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));});
 await page.locator('#selectionNote').click();await page.locator('#noteForm [name=note]').fill('第二页滚动批注');await page.getByRole('button',{name:'保存批注',exact:true}).click();await page.locator('[data-paper-page="2"] mark').waitFor();
 const notes=(await (await page.request.get('http://127.0.0.1:31992/api/state')).json()).annotations;assert.equal(notes.find(n=>n.note==='第二页滚动批注').page,2);
 await page.locator('[data-view=vocabulary]').click();await page.locator('#resumeReader').click();await page.waitForFunction(()=>document.querySelector('#prevPage')?.nextElementSibling.textContent==='2 / 3');assert.equal(await page.locator('#sideFontValue').textContent(),'16px');
 await page.reload();await page.locator('#resumeReader').click();await page.waitForFunction(()=>document.querySelector('#prevPage')?.nextElementSibling.textContent==='2 / 3');
 await page.locator('#pdfMode').click();await page.locator('[data-paper-page="2"] canvas').waitFor({timeout:15000});await page.waitForFunction(()=>document.querySelector('[data-paper-page="2"] .textLayer')?.textContent.includes('plasma'));
 const initialWidth=await page.locator('[data-paper-page="2"] canvas').evaluate(c=>c.width);await page.locator('#zoomIn').click();await page.waitForFunction(w=>document.querySelector('[data-paper-page="2"] canvas')?.width>w,initialWidth);await page.locator('#zoomReset').click();await page.locator('[data-paper-page="2"] canvas').waitFor();
 await page.locator('#paper').hover();await page.mouse.wheel(0,1200);await page.waitForFunction(()=>document.querySelector('#prevPage').nextElementSibling.textContent==='3 / 3');await page.waitForFunction(()=>document.querySelector('[data-paper-page="3"] .textLayer')?.textContent.includes('Page 3'));await page.locator('#prevPage').click();await page.waitForFunction(()=>document.querySelector('#prevPage').nextElementSibling.textContent==='2 / 3');
 await page.locator('#pagedLayout').click();await page.locator('[data-paper-page="2"] canvas').waitFor();assert.equal(await page.locator('[data-paper-page]').count(),1);await page.locator('#nextPage').click();await page.locator('[data-paper-page="3"] canvas').waitFor();assert.equal(await page.locator('[data-paper-page]').count(),1);
 await page.locator('#continuousLayout').click();await page.locator('[data-paper-page="3"] canvas').waitFor();assert.equal(await page.locator('[data-paper-page]').count(),3);await page.locator('#prevPage').click();
 await page.locator('#textMode').click();await page.locator('#pagedLayout').click();assert.equal(await page.locator('[data-paper-page]').count(),1);assert.equal(await page.locator('[data-paper-page]').getAttribute('data-paper-page'),'2');await page.locator('#prevPage').click();assert.equal(await page.locator('[data-paper-page]').getAttribute('data-paper-page'),'1');await page.locator('#continuousLayout').click();assert.equal(await page.locator('[data-paper-page]').count(),3);
 await page.locator('#lookupInput').fill('electric field');await page.getByRole('button',{name:'查询释义'}).click();await page.locator('#contextResults .context-card').first().waitFor();
 await page.locator('.term-editor summary').click();await page.locator('#preferredTerm').fill('瞬态电场');await page.locator('#saveTerm').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('专业译法已保存'));
 await page.locator('#reextractText').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('文字提取已优化')||document.querySelector('#toast').textContent.includes('为保护批注'));assert.equal(await page.locator('mark').count(),2);
 mkdirSync(resolve('test-results'),{recursive:true});await page.screenshot({path:'test-results/reader.png',fullPage:true});
 await page.locator('[data-view=review]').click();await page.locator('#reveal').click();await page.locator('[data-rating=good]').click();await page.getByRole('heading',{name:'当前没有到期词汇'}).waitFor();
 await page.locator('[data-view=library]').click();await page.mouse.move(800,100);await page.screenshot({path:'test-results/library.png',fullPage:true});
 await page.setViewportSize({width:760,height:1000});await page.screenshot({path:'test-results/narrow.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.deepEqual(errors,[]);console.log('PASS: PDF/TXT 导入、原版文本层、选词批注、释义收藏、跨文献例句、翻卡评分、窄屏布局；无浏览器异常。');
 const help=await browser.newPage({viewport:{width:1280,height:900}});await help.goto('http://127.0.0.1:31992/guide');await help.getByRole('heading',{name:'3. 普通联网：最简单的配置方法',exact:true}).waitFor();await help.screenshot({path:'test-results/guide.png',fullPage:false});await help.close();console.log('PASS: 双模式、文本/PDF 缩放、右栏字号、跨页面及刷新后继续阅读、音标与双语多义项、项目术语、重提文字保留批注。');
 if(process.env.LIVE_NETWORK==='1'){
   const current=await (await page.request.get('http://127.0.0.1:31992/api/state')).json();
   await page.request.post('http://127.0.0.1:31992/api/settings',{data:{...current.settings,online:true}});
   const lookup=await (await page.request.post('http://127.0.0.1:31992/api/lookup',{data:{q:'electric field',projectId:current.projects[0].id}})).json();assert.ok(lookup.meaning.includes('电场'));assert.equal(lookup.error,'');
   const corpus=await (await page.request.post('http://127.0.0.1:31992/api/corpus',{data:{q:'electric field',projectId:current.projects[0].id}})).json();assert.ok(Array.isArray(corpus.results));console.log('LIVE corpus results:',corpus.results.length);
   const sentence=await (await page.request.post('http://127.0.0.1:31992/api/lookup',{data:{q:'The electric field increases during the discharge.',kind:'sentence',projectId:current.projects[0].id}})).json();assert.match(sentence.translation,/[\u4e00-\u9fff]/);assert.ok(sentence.technicalTerms.some(t=>t.zh==='瞬态电场'));console.log('LIVE full sentence:',sentence.translation);
   const imported=await (await page.request.post('http://127.0.0.1:31992/api/import',{data:{name:'online-summary.txt',projectId:current.projects[0].id,content:Buffer.from('Abstract We measure the electric field in plasma using spectroscopy. The results demonstrate that electron density increases during the discharge.').toString('base64')}})).json();
   let complete;const deadline=Date.now()+90000;
   do{complete=await (await page.request.get('http://127.0.0.1:31992/api/document/'+imported.id)).json();if(complete.summary.status!=='processing')break;await new Promise(r=>setTimeout(r,500));}while(Date.now()<deadline);
   assert.equal(complete.summary.status,'ready',complete.summary.error);assert.match(complete.summary.zh,/[\u4e00-\u9fff]/);console.log('PASS: 实际联网释义、科研论文检索、导入后自动生成中英文概要。');
 }
}finally{if(browser)await browser.close();await new Promise(r=>{if(server.exitCode!==null)return r();server.once('exit',r);server.kill();});rmSync(tmp,{recursive:true,force:true});}
