import {test} from 'node:test';
import assert from 'node:assert/strict';
import {memoryState,intervalFor,schedule} from '../memory.mjs';
import {makeTranslationService,pageBlocks} from '../translation.mjs';
import {makeDictionary} from '../dictionary.mjs';
import {xmlBody,fulltextLocation,makeCorpus} from '../corpus.mjs';
import {offlineIPA} from '../ipa.mjs';
import {termRanges} from '../public/reading-marks.js';
import {orderedBlocks,flowMarkup} from '../public/translation-flow.js';
import {researchLookup} from '../lookup.mjs';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
test('measurement 离线音标、完整词边界和流式译文完整性',()=>{assert.match(offlineIPA('measurement'),/英 .*美 /);assert.equal(termRanges('plasma plasmatic PLASMA',[{term:'plasma',meaning:'等离子体'}]).length,2);assert.equal(termRanges('C++ method',[{term:'C++',meaning:'语言'}]).length,1);const text='译文'.repeat(3000),page={number:1,width:600,blocks:[{id:'x',x:40,y:50,width:220,height:10,text,source:'Long text.'}]};assert.ok(flowMarkup(page).includes(text));assert.equal(orderedBlocks(page)[0].id,'x');});
test('词典补充在已有内置义项时仍返回新义项，失败明确返回错误',async()=>{const deps={settings:()=>({online:true}),ai:()=>{},translate:async x=>'译文：'+x,fetchJSON:async()=>[{meanings:[{partOfSpeech:'noun',definitions:[{definition:'Additional scientific sense.',example:'A teaching example.'}]}]}]};const success=await researchLookup({q:'plasma'},deps);assert.equal(success.senses[0].en,'Additional scientific sense.');assert.match(success.senses[0].exampleZh,/教学|译文/);const failure=await researchLookup({q:'plasma'},{...deps,fetchJSON:async()=>[]});assert.match(failure.error,/补充词典失败/);assert.ok(failure.meaning);});
test('在线词典断网时回退本地 WordNet 真实义项',async()=>{const dictionary=makeDictionary(async()=>{throw Error('offline');}),rows=await dictionary.entries('measurement');assert.equal(rows[0].dictionarySource,'本地 WordNet 3.1');assert.match(rows[0].meanings[0].definitions[0].definition,/assigning numbers to phenomena/i);});
test('遗忘曲线随时间下降，高目标缩短间隔，复习重置记忆率',()=>{
 const card={interval:3,due:3*86400000,lastReviewed:0,stability:3,reps:2,ease:2.5};assert.equal(memoryState(card,0).retention,1);assert.ok(Math.abs(memoryState(card,3*86400000).retention-.9)<1e-10);assert.ok(memoryState(card,6*86400000).retention<.9);assert.ok(intervalFor(3,.95)<intervalFor(3,.9));const next=schedule(card,'good',3*86400000,.95);assert.equal(memoryState(next,next.lastReviewed).retention,1);assert.ok(next.stability>card.stability);assert.equal(schedule(card,'again',0).due,600000);assert.throws(()=>schedule(card,'good',0,1));
});
test('正文仅提取 body，排除摘要，外部全文地址不能任意指定',()=>{
 const parts=xmlBody('<article><abstract><p>abstract plasma</p></abstract><body><sec><title>Methods</title><p>The plasma &amp; field were measured.</p></sec></body></article>');assert.equal(parts.length,1);assert.equal(parts[0].section,'Methods');assert.match(parts[0].text,/plasma & field/);assert.equal(fulltextLocation({pdf:'http://127.0.0.1/secret'}),null);assert.equal(fulltextLocation({pmcid:'../../secret'}),null);assert.equal(fulltextLocation({pdf:'https://arxiv.org/pdf/2401.12345'}).type,'pdf');
});
test('音标本地即返，未知词请求去重，失败负缓存',async()=>{
 let calls=0;const dictionary=makeDictionary(async()=>{calls++;await delay(5);throw Error('timeout');});assert.match((await dictionary.pronunciation('plasma',true)).phonetic,/plæz/);assert.equal(calls,0);await Promise.all([dictionary.entries('zzpaperlexunknown'),dictionary.entries('zzpaperlexunknown')]);await dictionary.entries('zzpaperlexunknown');assert.equal(calls,1);assert.equal((await dictionary.pronunciation('zzpaperlexunknown',true)).status,'unavailable');
});
function store(){const records=new Map();return {get:(k,id)=>{const v=records.get(k+id);if(!v)throw Error('not found');return structuredClone(v);},put:(k,v)=>{records.set(k+v.id,structuredClone(v));return v;},all:k=>[...records].filter(([key])=>key.startsWith(k)).map(([,v])=>structuredClone(v))};}
test('全文翻译后台完成全篇，手动修改不被在途翻译覆盖，重启可继续编辑',async()=>{
 const db=store();db.put('project',{id:'p',topic:'plasma'});db.put('document',{id:'d',ext:'.txt',title:'Paper',projectId:'p',pages:[{text:'First paragraph.\n\nSecond paragraph.'}]});let release,started;const entered=new Promise(r=>started=r);let count=0;
 const options={...db,settings:()=>({online:true}),readFile:()=>{},ai:()=>{},translate:async()=>{if(++count===1){started();await new Promise(r=>release=r);}return '自动译文';}},service=makeTranslationService(options),url=new URL('http://localhost/?id=d');
 const draft=await service.prepare('d');assert.equal(draft.pages[0].blocks.length,2);await service.handle('/api/translation/start',{id:'d'},url);await entered;const block=draft.pages[0].blocks[0];await service.handle('/api/translation/edit',{id:'d',blockId:block.id,revision:0,text:'人工校对的科研译文',x:45,y:50,width:505,height:70,fontSize:12},url);release();while(service.active.size)await delay(5);const done=await service.prepare('d');assert.equal(done.status,'complete');assert.equal(done.pages[0].blocks[0].text,'人工校对的科研译文');assert.equal(done.pages[0].blocks[1].text,'自动译文');await assert.rejects(service.handle('/api/translation/edit',{id:'d',blockId:block.id,revision:0,text:'stale'},url),e=>e.status===409);assert.equal((await makeTranslationService(options).prepare('d')).pages[0].blocks[0].text,'人工校对的科研译文');
});
test('PDF 译框保留双栏坐标，不跨栏合并；开放正文缓存可离线重复检索',async()=>{
 const items=[{str:'Left scientific paragraph',transform:[1,0,0,10,40,700],height:10,width:100},{str:'Right scientific paragraph',transform:[1,0,0,10,330,700],height:10,width:100}];const blocks=pageBlocks(items,{width:600,convertToViewportPoint:(x,y)=>[x,800-y]});assert.equal(blocks.length,2);assert.equal(blocks[1].x,329);
 const db=store();let online=true,calls=0;db.put('paper',{id:'paper:one',title:'P',engine:'Europe PMC',url:'https://europepmc.org/articles/PMC123',pmcid:'PMC123'});const corpus=makeCorpus({...db,settings:()=>({online}),fetchJSON:()=>{},download:async()=>{calls++;return Buffer.from('<body><title>Results</title><p>Plasma density increases.</p></body>');}});assert.equal((await corpus.fulltext({id:'paper:one',q:'plasma'})).results[0].section,'Results');online=false;assert.equal((await corpus.fulltext({id:'paper:one',q:'density'})).results.length,1);assert.equal(calls,1);
});

test('非居中双栏按栏组段，保留首行缩进与逐行坐标',()=>{
 const make=(str,x,y,w)=>({str,transform:[1,0,0,10,x,800-y],height:10,width:w});
 const items=[make('Full width scientific title',40,40,500),make('Left first indented line',52,90,200),make('Left continuation line.',40,103,224),make('Left second paragraph',52,135,200),make('Left second continuation.',40,148,224),make('Right first paragraph',290,90,270),make('Right continued line.',290,103,270),make('Right second paragraph',300,135,250),make('Right continued conclusion.',290,148,270)];
 const blocks=pageBlocks(items,{width:600,convertToViewportPoint:(x,y)=>[x,800-y]});assert.deepEqual(blocks.map(b=>b.column),['full','left','left','right','right']);assert.match(blocks[1].source,/Left first indented line Left continuation/);assert.equal(blocks[1].x,39);assert.equal(blocks[1].sourceRects.length,2);for(const b of blocks.filter(b=>b.column==='left'))assert.ok(b.sourceRects.every(r=>r.x+r.width<280));for(const b of blocks)assert.ok(!(b.source.includes('Left')&&b.source.includes('Right')));
});

test('窄栏间隙先分栏，防止左右正文拼接',()=>{const items=[];for(let n=0;n<5;n++){for(const [x,str] of [[40,'Left scientific text'],[310,'Right scientific text']])items.push({str,transform:[1,0,0,10,x,700-n*13],height:10,width:260});}const b=pageBlocks(items,{width:612,convertToViewportPoint:(x,y)=>[x,792-y]});assert.equal(b.length,2);assert.deepEqual(b.map(x=>x.column),['left','right']);assert.ok(b.every(x=>x.sourceRects.length===5));});
test('旧 PDF 译稿重建保留匹配译文和未匹配人工译文',async()=>{
 const content='BT /F1 12 Tf 40 700 Td (First scientific paragraph.) Tj ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [4 0 R] /Count 1 >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents 5 0 R >>','<< /Length '+content.length+' >>\nstream\n'+content+'\nendstream'];let pdf='%PDF-1.4\n',offsets=[];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const offset=Buffer.byteLength(pdf);pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+offset+'\n%%EOF';
 const db=store();db.put('document',{id:'d',ext:'.pdf',title:'Paper',projectId:'p'});db.put('translation',{id:'translation:d',documentId:'d',ext:'.pdf',status:'paused',pages:[{number:1,blocks:[{id:'a',source:'First scientific paragraph.',text:'已校正译文',status:'edited',revision:2},{id:'b',source:'Old merged columns',text:'必须保留的旧译文',status:'edited'}]}]});const service=makeTranslationService({...db,settings:()=>({}),readFile:()=>Buffer.from(pdf)}),draft=await service.prepare('d');assert.equal(draft.layoutVersion,2);assert.equal(draft.pages[0].blocks[0].text,'已校正译文');assert.equal(draft.unmatchedTranslations[0].text,'必须保留的旧译文');assert.deepEqual(await service.prepare('d'),draft);
});

test('重复选区去重且同一行只绘制单下划线',async()=>{const {mergeRects,underlineRects}=await import('../public/pdf-anchor.js');const rects=[{x:.1,y:.1,width:.3,height:.02},{x:.12,y:.101,width:.1,height:.018},{x:.1,y:.13,width:.3,height:.02}];const under=underlineRects(rects);assert.equal(under.length,2);const union=mergeRects(rects);for(let i=0;i<union.length;i++)for(let j=i+1;j<union.length;j++){const a=union[i],b=union[j];assert.ok(Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x)<1e-8||Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y)<1e-8);}});
test('两段并行、临时错误重试与模型拒绝连接明确暂停',async()=>{const db=store();db.put('project',{id:'p',topic:'plasma'});db.put('document',{id:'d',ext:'.txt',title:'Paper',projectId:'p',pages:[{text:'First paragraph.\n\nSecond paragraph.\n\nThird paragraph.'}]});let live=0,max=0,calls=0;const opts={...db,settings:()=>({online:true}),readFile:()=>{},translate:async()=>{const attempt=++calls;live++;max=Math.max(max,live);await delay(10);live--;if(attempt===1)throw Error('temporary');return '译文';}},service=makeTranslationService(opts);await service.handle('/api/translation/start',{id:'d',concurrency:2},new URL('http://x'));while(service.active.size)await delay(10);assert.equal(max,2);assert.equal(calls,4);assert.equal((await service.prepare('d')).status,'complete');
 const draft=await service.prepare('d');draft.pages[0].blocks[0].status='error';draft.pages[0].blocks[0].text='';db.put('translation',draft);const failing=makeTranslationService({...opts,translate:async()=>{throw Object.assign(Error('请启动本机模型'),{code:'ECONNREFUSED'});}});await failing.handle('/api/translation/start',{id:'d'},new URL('http://x'));while(failing.active.size)await delay(5);const failed=await failing.prepare('d');assert.equal(failed.status,'paused');assert.match(failed.lastError,/启动本机模型/);assert.equal(failed.pages[0].blocks[1].text,'译文');});

test('收藏语境按完整句界提取，不按固定长度截断',async()=>{const {sentenceContext}=await import('../public/sentence-context.js');const full='The plasma '+('provides stable measurements and '.repeat(30))+'remains stable.';assert.equal(sentenceContext('Earlier result. '+full+' Next result.','plasma'),full);assert.equal(sentenceContext('The electric\nfield increases. Another sentence.','electric field'),'The electric field increases.');});
test('显式联网翻译绕过不可用模型，模型配置与已完成段落保留',async()=>{const db=store();db.put('project',{id:'p',topic:'plasma'});db.put('document',{id:'d',ext:'.txt',title:'Paper',projectId:'p',pages:[{text:'First paragraph.\n\nSecond paragraph.'}]});let modelCalls=0,onlineCalls=0;const service=makeTranslationService({...db,settings:()=>({online:true,aiEnabled:true}),readFile:()=>{},ai:async()=>{modelCalls++;throw Error('offline model');},translate:async(text,options)=>{assert.equal(options.basic,true);onlineCalls++;return '联网译文';}});const draft=await service.prepare('d');await service.handle('/api/translation/edit',{id:'d',blockId:draft.pages[0].blocks[0].id,revision:0,text:'已校对译文'},new URL('http://x'));await service.handle('/api/translation/start',{id:'d',provider:'online'},new URL('http://x'));while(service.active.size)await delay(5);const result=await service.prepare('d');assert.equal(modelCalls,0);assert.equal(onlineCalls,1);assert.equal(result.provider,'online');assert.equal(result.status,'complete');assert.equal(result.pages[0].blocks[0].text,'已校对译文');});


test('DeepL 请求、缓存与额度错误；本地中文查词不使用网络',async()=>{
 const {makeDeepL}=await import('../deepl.mjs');const db=store();let calls=0,plan='free';const engine=makeDeepL({...db,settings:()=>({online:true,deeplKey:'test-key',deeplPlan:plan}),fetchJSON:async(url,opts)=>{calls++;assert.equal(url,'https://api-free.deepl.com/v2/translate');assert.equal(opts.headers.Authorization,'DeepL-Auth-Key test-key');assert.equal(JSON.parse(opts.body).target_lang,'ZH');return {translations:[{text:'电场测量。'}]};}});
 assert.deepEqual(await Promise.all([engine('Measurement.'),engine('Measurement.')]),['电场测量。','电场测量。']);assert.equal(calls,1);await engine('Measurement.');assert.equal(calls,1);
 const bad=makeDeepL({...db,settings:()=>({online:true,deeplKey:'x',deeplPlan:'pro'}),fetchJSON:async url=>{assert.match(url,/api.deepl.com/);throw Object.assign(Error('quota'),{status:456});}});await assert.rejects(bad('Another sentence.'),/额度耗尽/);
 const fail=()=>{throw Error('不应访问网络');};const r=await researchLookup({q:'measurement',skipDictionary:true},{settings:()=>({online:true}),ai:fail,translate:fail,fetchJSON:fail});assert.match(r.meaning,/测量|度量/);assert.ok(r.phonetic);
});
test('MyMemory 串行去重、持久缓存与额度熔断',async()=>{
 const {makeOnlineTranslation}=await import('../online-translation.mjs');const db=store();let calls=0;const deps={...db,settings:()=>({}),wait:async()=>{},fetchJSON:async()=>{calls++;return {responseStatus:200,responseData:{translatedText:'译文'}};}};const run=makeOnlineTranslation(deps);await Promise.all([run('Same sentence.'),run('Same sentence.')]);assert.equal(calls,1);await makeOnlineTranslation(deps)('Same sentence.');assert.equal(calls,1);
 const quota=makeOnlineTranslation({...deps,fetchJSON:async()=>{calls++;return {quotaFinished:true};}});await assert.rejects(quota('new'),/额度已用完/);await assert.rejects(quota('other'),/额度已用完/);assert.equal(calls,2);
});
test('DeepL 全文任务正确选路，配额耗尽停止后续发送',async()=>{
 const db=store();db.put('project',{id:'p',topic:'electric field'});db.put('document',{id:'d',ext:'.txt',title:'Paper',projectId:'p',pages:[{text:'First paragraph.\n\nSecond paragraph.'}]});let calls=0;const service=makeTranslationService({...db,settings:()=>({online:true,deeplKey:'key'}),deepl:async()=>{calls++;throw Object.assign(Error('DeepL 额度耗尽'),{status:456});},ai:()=>{throw Error('wrong route');},translate:()=>{throw Error('wrong route');}});await service.handle('/api/translation/start',{id:'d',provider:'deepl',concurrency:1},new URL('http://localhost'));while(service.active.size)await delay(5);assert.equal(calls,1);assert.equal((await service.prepare('d')).status,'paused');
});
